export const Posts = [
  {
    title: 'Set Up Blazing Fast Frontend Development Experience With Vite',
    subtitle: 'Replace create-react-app, VueCLI, Webpack, and much more',
    img: 'https://i.imgur.com/c5RJXXP.jpg',
    thumbnail: 'https://i.imgur.com/c5RJXXP.jpg',
    path: 'set-up-blazing-fast-frontend-development-experience-with-vite',
    postDate: new Date('1 Nov 2021'),
    tags: ['#webdev', '#frontend', '#javascript'],
  },
  {
    title: 'Position Absolute and Relative — The Simplest Guide',
    subtitle: 'Simple properties that can seem hard',
    path: 'position-absolute-relative-the-simplest-guide',
    img: 'https://dev-to-uploads.s3.amazonaws.com/uploads/articles/jmoe6qiwmx4pmf1kujx5.jpg',
    thumbnail: 'https://i.imgur.com/uc21JTK.jpg',
    postDate: new Date('25 Oct 2021'),
    tags: ['#css', '#webdev', '#beginners', '#tutorial'],
  },
  {
    title: '11 Reasons Why Software Engineering Isn’t a Stressful Job',
    subtitle: 'Very unpopular opinion',
    path: '11-reasons-why-software-engineering-isnt-a-stressful-job',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--RuvFUyiE--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/n1mbmvfdriyxp03ycw0f.jpg',
    thumbnail: 'https://i.imgur.com/d0mmoCy.jpg',
    postDate: new Date('14 Sep 2021'),
    tags: ['#career'],
  },
  {
    title: 'Creating Responsive Web Apps Is Ridiculously Simple ',
    subtitle: "Media queries don't have to be hard.",
    path: 'a-ridiculously-simple-way-for-creating-responsive-web-apps',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--PiHQnn8C--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/gcgc04yohazkor9jknkz.jpg',
    thumbnail: 'https://i.imgur.com/v5AheZe.jpg',
    postDate: new Date('8 Sep 2021'),
    tags: ['#webdev', '#css', '#html', '#frontend'],
  },
  {
    title: 'All CSS Properties You Need to Know to Build a Website',
    subtitle: 'It’s easy to get lost in them',
    path: 'all-css-properties-you-need-to-know-to-build-a-website',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--hae0usDJ--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/5v01dcypq4px8ilwnbal.jpg',
    thumbnail: 'https://i.imgur.com/XGc2pJl.jpg',
    postDate: new Date('23 Aug 2021'),
    tags: ['#css', '#webdev', '#html'],
  },
  {
    title: '14 VS Code Shortcuts to Supercharge Your Productivity',
    subtitle: 'Visual Studio Code shortcuts to supercharge your productivity.',
    path: '14-vs-code-shortcuts-to-supercharge-your-productivity',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--j05vcwMq--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/1m0hjjyxqef2puz6m7qa.jpg',
    thumbnail: 'https://i.imgur.com/Bxc1Dxy.jpg',
    postDate: new Date('26 Jul 2021'),
    tags: ['#vscode', '#productivity', '#javascript', '#tooling'],
  },
  {
    title: '11 Git Commands I Use Every Day',
    subtitle: 'Essential git commands every dev should know',
    path: '11-git-commands-i-use-every-day',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--_1L1jPde--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/f5845dmeznxm4iju2244.jpg',
    thumbnail: 'https://i.imgur.com/n8QbPkb.jpg',
    postDate: new Date('16 Jul 2021'),
    tags: ['#git', '#github', '#programming', '#codequality'],
  },
  {
    title: 'How To Structure a Massive Vuex Store for a Production App',
    subtitle: 'Dive deep into a store with 1,000+ properties',
    path: 'how-to-structure-a-massive-vuex-store-for-a-production-app',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--NYrsDUAE--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/0q6yjo8ayj9g7gx55aeh.jpg',
    thumbnail: 'https://i.imgur.com/G3pOkrc.jpg',
    postDate: new Date('9 Jul 2021'),
    tags: ['#vue', '#javascript', '#webdev', '#programming'],
  },
  {
    title: 'How I Prioritize My Work as a Software Engineer',
    subtitle: 'Soft skills that completely transformed my career',
    path: 'how-i-prioritize-my-work-as-a-software-engineer',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--iwwhk5dg--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/jz0pu5cze0jzdh89qadp.jpg',
    thumbnail: 'https://i.imgur.com/2Y485qA.jpg',
    postDate: new Date('8 Jun 2021'),
    tags: ['#productivity', '#career', '#wizz'],
  },
  {
    title: 'How To Properly Use Frontend UI Component Libraries',
    subtitle:
      'Vuetify, Material-UI, React Bootstrap — how to use them with the minimal maintenance',
    path: 'how-to-properly-use-frontend-ui-component-libraries',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--fjg33pdh--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/sdh5zgcpn8r2gwj1qc7y.jpg',
    thumbnail: 'https://i.imgur.com/RcoV1H2.jpg',
    postDate: new Date('23 May 2021'),
    tags: ['#javascript', '#react', '#vue', '#frontend'],
  },
  {
    title: 'Vue.js vs. React — Not Your Usual Comparison',
    subtitle: 'Why does one of them seem so familiar?',
    path: 'vue-js-vs-react-not-your-usual-comparison',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--JRJ-hZN---/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/hlfo65eknox353dwi7ez.jpg',
    thumbnail: 'https://i.imgur.com/oudnhxu.jpg',
    postDate: new Date('13 May 2021'),
    tags: ['#vue', '#react', '#javascript', '#frontend'],
  },
  {
    title: 'Why is the Virtual DOM So Fast?',
    subtitle: 'Is it some kind of black magic?',
    path: 'why-is-the-virtual-dom-so-fast',
    img: 'https://res.cloudinary.com/practicaldev/image/fetch/s--qIYWrik5--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/s0i9fihpvbpncpy03b54.jpg',
    thumbnail: 'https://i.imgur.com/2dykCiK.jpg',
    postDate: new Date('11 May 2021'),
    tags: ['#webdev', '#javascript', '#react'],
  },
];
